---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vector
  namespace: vector
spec:
  serviceName: vector
  replicas: 1
  template:
    metadata:
      labels:
        app: vector
    spec:
      volumes:
        - name: vector-config
          configMap:
            name: vector-config
      containers:
        - name: vector
          image: timberio/vector:0.34.1-debian
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /etc/vector/
              name: vector-config
  selector:
    matchLabels:
      app: vector
