---
apiVersion: v1
kind: Service
metadata:
  name: vector
  namespace: vector
  labels:
    app: vector
spec:
  type: NodePort
  ports:
    - port: 8686
      name: service
      targetPort: 8686
      nodePort: 8686
  selector:
    app: vector